export type Property = {
    id?: string,
    location: string,
    type: string,
    amenities: string[],
    petFriendly?: boolean,
    size: number,
    bathrooms: number,
    bedrooms: number,
    beds: number,
    bedroomsBeds: {single: number, double: number}[],
    pics: string[],
    primaryImage?: string,
    childrenAllowed?: boolean,
    smokingAllowed?: boolean,
    private?: boolean,
    lat?: number,
    lon?: number,
}