// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elweutkgdoftooxpakyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsd2V1dGtnZG9mdG9veHBha3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTY0OTIsImV4cCI6MjA3MTU3MjQ5Mn0.I35xRhFf_lfXSrYWyde_stcl8GRBUq08BUX-l7kOnRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});